import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Sidebar from "./components/page";

export const metadata: Metadata = {
  title: "DevVault",
  description: "Generated by DevVault",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {children}
      <body>
        <Sidebar />
        <h1 className="ABC">DevVault</h1>
      </body>
    </html>


  );
}
