import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

export const metadata: Metadata = {
  title: "DevVault",
  description: "Generated by DevVault",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {children}
      <body>
        <p>
          <nav>
            <Link href="/app">Home</Link>
          </nav>
        </p>
        <p>
          <nav>
            <Link href="/React">React</Link>
          </nav>
        </p>
        <p>
          <nav>
            <Link href="/Next.js">Next.js</Link>
          </nav>
        </p>
        <p>
          <nav>
            <Link href="/JavaScript">JavaScript</Link>
          </nav>
        </p>
        <p>
          <nav>
            <Link href="/TypeScript">TypeScript</Link>
          </nav>
        </p>
      </body>
    </html>


  );
}
