import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Sidebar from "./components/page";

export const metadata: Metadata = {
  title: "DevVault",
  description: "Generated by DevVault",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ background: "black", color: "white", padding: "20px", display: "flex", flexDirection: "column", minHeight: "100vh", justifyContent: "flex-start" }}>
         {/* <Sidebar /> */}
         {/* <h1 style={{color:}}>DevVault</h1> */}
        {children}
        <h1 style={{ textAlign: "center" }}>-DevVault (⌐■_■)</h1>
      </body>
    </html>


  );
}
